# Generated by Django 5.2.4 on 2025-07-14 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(verbose_name='Nome')),
                ('data_prevista_entrega', models.DateField(verbose_name='Data Prevista para Entrega')),
                ('data_entrega', models.DateField(blank=True, null=True, verbose_name='Data da Entrega')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.disciplina', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Trabalho',
                'verbose_name_plural': 'Trabalhos',
            },
        ),
    ]
