# Generated by Django 5.2.5 on 2025-08-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_trabalho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
